# Generated by Django 3.2.8 on 2021-10-15 18:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.CharField(default='JohnSmith@abc.edu', max_length=1000)),
                ('experiment_time_zone', models.CharField(default='US/Pacific', max_length=1000)),
                ('site_url', models.CharField(default='http://localhost:8000', max_length=200)),
                ('test_email_account', models.CharField(default='', max_length=1000)),
                ('channel_key', models.UUIDField(default=uuid.uuid4, verbose_name='Channel Key')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parameters',
                'verbose_name_plural': 'Parameters',
            },
        ),
    ]
