# Generated by Django 3.2.8 on 2021-10-15 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Study Parameter Set',
                'verbose_name_plural': 'Study Parameter Sets',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='*** New Session ***', max_length=300)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('channel_key', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Channel Key')),
                ('session_key', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Session Key')),
                ('started', models.BooleanField(default=False)),
                ('current_period', models.IntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('shared', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('soft_delete', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.parameterset')),
            ],
            options={
                'verbose_name': 'Experiment Session',
                'verbose_name_plural': 'Experiment Sessions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SessionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_periods', to='main.session')),
            ],
            options={
                'verbose_name': 'Session Period',
                'verbose_name_plural': 'Session Periods',
                'ordering': ['period_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='sessionperiod',
            constraint=models.UniqueConstraint(fields=('session', 'period_number'), name='unique_SD'),
        ),
    ]
