# Generated by Django 3.2.8 on 2021-10-18 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211015_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('Blue', 'Blue'), ('Red', 'Red')], default='Blue', max_length=100)),
                ('good_one_amount', models.IntegerField(default=1, verbose_name='Good One Amount')),
                ('good_two_amount', models.IntegerField(default=1, verbose_name='Good Two Amount')),
                ('good_one_label', models.CharField(default='Blue', max_length=10, verbose_name='Good One Label')),
                ('good_two_label', models.CharField(default='Red', max_length=10, verbose_name='Good One Label')),
                ('good_one_rgb_color', models.CharField(default='#6495ED', max_length=10, verbose_name='Good One RGB Color')),
                ('good_two_rgb_color', models.CharField(default='#DC143C', max_length=10, verbose_name='Good Two RGB Color')),
                ('good_one_production_1', models.DecimalField(decimal_places=9, default=0, max_digits=10, verbose_name='Good One Production Parameter 1')),
                ('good_one_production_2', models.DecimalField(decimal_places=9, default=0, max_digits=10, verbose_name='Good One Production Parameter 2')),
                ('good_one_production_3', models.DecimalField(decimal_places=9, default=0, max_digits=10, verbose_name='Good One Production Parameter 3')),
                ('good_two_production_1', models.DecimalField(decimal_places=9, default=0, max_digits=10, verbose_name='Good Two Production Parameter 1')),
                ('good_two_production_2', models.DecimalField(decimal_places=9, default=0, max_digits=10, verbose_name='Good Two Production Parameter 2')),
                ('good_two_production_3', models.DecimalField(decimal_places=9, default=0, max_digits=10, verbose_name='Good Two Production Parameter 3')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parameter Set Type',
                'verbose_name_plural': 'Parameter Set Type',
            },
        ),
        migrations.AlterModelOptions(
            name='parameterset',
            options={'verbose_name': 'Parameter Set', 'verbose_name_plural': 'Parameter Sets'},
        ),
        migrations.AddField(
            model_name='parameterset',
            name='allow_stealing',
            field=models.BooleanField(default=True, verbose_name='Allow Stealing'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='break_period_frequency',
            field=models.IntegerField(default=7, verbose_name='Break Period Fequency (Periods)'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='period_count',
            field=models.IntegerField(default=20, verbose_name='Number of periods'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='period_length_production',
            field=models.IntegerField(default=10, verbose_name='Period Length, Production'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='period_length_trade',
            field=models.IntegerField(default=10, verbose_name='Period Length, Trade'),
        ),
        migrations.CreateModel(
            name='ParameterSetTypePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_label', models.CharField(default='1', max_length=1, verbose_name='ID Label')),
                ('location', models.IntegerField(default=1, verbose_name='Location number (1-8)')),
                ('period_groups', models.JSONField(default=dict, verbose_name='Group by period')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_type_players', to='main.parametersettype')),
            ],
            options={
                'verbose_name': 'Parameter Set Type Player',
                'verbose_name_plural': 'Parameter Set Type Players',
                'ordering': ['id_label'],
            },
        ),
        migrations.AddField(
            model_name='parametersettype',
            name='parameter_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_types', to='main.parameterset'),
        ),
        migrations.AddConstraint(
            model_name='parametersettype',
            constraint=models.UniqueConstraint(fields=('parameter_set', 'subject_type'), name='unique_player_type'),
        ),
    ]
