# Generated by Django 3.2.8 on 2021-10-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211018_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametersettype',
            name='good_one_label',
        ),
        migrations.RemoveField(
            model_name='parametersettype',
            name='good_one_rgb_color',
        ),
        migrations.RemoveField(
            model_name='parametersettype',
            name='good_two_label',
        ),
        migrations.RemoveField(
            model_name='parametersettype',
            name='good_two_rgb_color',
        ),
        migrations.AddField(
            model_name='parameterset',
            name='good_one_label',
            field=models.CharField(default='Blue', max_length=10, verbose_name='Good One Label'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='good_one_rgb_color',
            field=models.CharField(default='#6495ED', max_length=10, verbose_name='Good One RGB Color'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='good_two_label',
            field=models.CharField(default='Red', max_length=10, verbose_name='Good One Label'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='good_two_rgb_color',
            field=models.CharField(default='#DC143C', max_length=10, verbose_name='Good Two RGB Color'),
        ),
    ]
