# Generated by Django 3.2.8 on 2021-10-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211018_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersettypeplayer',
            name='id_label',
            field=models.CharField(default='1', max_length=2, verbose_name='ID Label'),
        ),
    ]
