# Generated by Django 3.2.8 on 2021-10-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_parametersettypeplayer_id_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='period_length_trade',
            field=models.IntegerField(default=90, verbose_name='Period Length, Trade'),
        ),
    ]
