# Generated by Django 3.2.8 on 2021-10-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_parameterset_period_length_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='good_one_label',
            field=models.CharField(default='Red', max_length=10, verbose_name='Good One Label'),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='good_one_rgb_color',
            field=models.CharField(default='#DC143C', max_length=10, verbose_name='Good One RGB Color'),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='good_two_label',
            field=models.CharField(default='Blue', max_length=10, verbose_name='Good One Label'),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='good_two_rgb_color',
            field=models.CharField(default='#6495ED', max_length=10, verbose_name='Good Two RGB Color'),
        ),
    ]
