# Generated by Django 3.2.8 on 2021-10-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211020_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersettype',
            name='subject_type',
            field=models.CharField(choices=[('One', 'One'), ('Two', 'Two')], default='One', max_length=100),
        ),
    ]
