# Generated by Django 3.2.8 on 2021-10-21 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_parametersettype_subject_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametersettype',
            options={'ordering': ['subject_type'], 'verbose_name': 'Parameter Set Type', 'verbose_name_plural': 'Parameter Set Type'},
        ),
    ]
