# Generated by Django 3.2.8 on 2021-10-22 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211021_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametersetplayer',
            options={'ordering': ['location'], 'verbose_name': 'Parameter Set Player', 'verbose_name_plural': 'Parameter Set Players'},
        ),
    ]
