# Generated by Django 3.2.8 on 2021-10-22 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_parametersetplayer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSetPlayerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.IntegerField(default=1, verbose_name='Group Number')),
                ('period', models.IntegerField(default=1, verbose_name='Period')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_player_groups', to='main.parametersetplayer')),
            ],
            options={
                'verbose_name': 'Parameter Set Player Group',
                'verbose_name_plural': 'Parameter Set Player Groups',
                'ordering': ['period'],
            },
        ),
    ]
