# Generated by Django 3.2.8 on 2021-10-28 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_parametersetplayergroup_unique_player_period_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_one_house', models.IntegerField(default=0, verbose_name='Good one in house')),
                ('good_two_house', models.IntegerField(default=0, verbose_name='Good two in house')),
                ('good_one_field', models.IntegerField(default=0, verbose_name='Good one in field')),
                ('good_two_field', models.IntegerField(default=0, verbose_name='Good two in field')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_players_paramterset', to='main.parametersetplayer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_players', to='main.session')),
            ],
            options={
                'verbose_name': 'Session Player',
                'verbose_name_plural': 'Session Players',
                'ordering': ['parameter_set_player__location'],
            },
        ),
    ]
