# Generated by Django 3.2.8 on 2021-11-04 21:38

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_sessionplayer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-start_date'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.CreateModel(
            name='SessionPlayerMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_one_amount', models.IntegerField(verbose_name='Good one amount')),
                ('good_two_amount', models.IntegerField(verbose_name='Good two amount')),
                ('source_container', models.CharField(choices=[('House', 'House'), ('Field', 'Field')], max_length=100)),
                ('target_container', models.CharField(choices=[('House', 'House'), ('Field', 'Field')], max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('session_player_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_player_move_sources', to='main.sessionplayer')),
                ('session_player_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_player_move_targets', to='main.sessionplayer')),
            ],
            options={
                'verbose_name': 'Session Player Move',
                'verbose_name_plural': 'Session Player Moves',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='sessionplayermove',
            constraint=models.CheckConstraint(check=models.Q(('good_one_amount__gte', 0)), name='good_one_amount__gte_0'),
        ),
        migrations.AddConstraint(
            model_name='sessionplayermove',
            constraint=models.CheckConstraint(check=models.Q(('good_two_amount__gte', 0)), name='good_two_amount__gte_0'),
        ),
        migrations.AddConstraint(
            model_name='sessionplayermove',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('session_player_source', django.db.models.expressions.F('session_player_target')), _negated=True), models.Q(('source_container', django.db.models.expressions.F('target_container')), _negated=True)), name='source_equals_target'),
        ),
    ]
