# Generated by Django 3.2.8 on 2021-11-04 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20211104_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayermove',
            name='session_period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='session_player_move_a', to='main.sessionperiod'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessionplayermove',
            name='session_player_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_player_move_b', to='main.sessionplayer'),
        ),
        migrations.AlterField(
            model_name='sessionplayermove',
            name='session_player_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_player_move_c', to='main.sessionplayer'),
        ),
    ]
