# Generated by Django 3.2.8 on 2021-11-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20211104_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='town_count',
            field=models.IntegerField(default=1, verbose_name='Town Count'),
        ),
    ]
