# Generated by Django 3.2.8 on 2021-11-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_parameterset_town_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameterset',
            old_name='good_two_label',
            new_name='good_b_label',
        ),
        migrations.RenameField(
            model_name='parameterset',
            old_name='good_two_rgb_color',
            new_name='good_b_rgb_color',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='good_one_label',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='good_one_rgb_color',
        ),
        migrations.AddField(
            model_name='parameterset',
            name='good_a_label',
            field=models.CharField(default='Orange', max_length=10, verbose_name='Good One Label'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='good_a_rgb_color',
            field=models.CharField(default='#FF5733', max_length=10, verbose_name='Good One RGB Color'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='good_c_label',
            field=models.CharField(default='Pink', max_length=10, verbose_name='Good One Label'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='good_c_rgb_color',
            field=models.CharField(default='#FF1493', max_length=10, verbose_name='Good Two RGB Color'),
        ),
    ]
