# Generated by Django 3.2.8 on 2021-11-10 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20211110_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametersettype',
            options={'ordering': ['subject_type'], 'verbose_name': 'Parameter Set Type', 'verbose_name_plural': 'Parameter Set Types'},
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='good_a_label',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='good_a_rgb_color',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='good_b_label',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='good_b_rgb_color',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='good_c_label',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='good_c_rgb_color',
        ),
        migrations.CreateModel(
            name='ParameterSetGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Orange', max_length=10, verbose_name='Good One Label')),
                ('rgb_color', models.CharField(default='#FF5733', max_length=10, verbose_name='Good One RGB Color')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_goods', to='main.parameterset')),
            ],
            options={
                'verbose_name': 'Parameter Set Good',
                'verbose_name_plural': 'Parameter Set Goods',
            },
        ),
        migrations.AddConstraint(
            model_name='parametersetgood',
            constraint=models.UniqueConstraint(fields=('label',), name='unique_good_label'),
        ),
        migrations.AddConstraint(
            model_name='parametersetgood',
            constraint=models.UniqueConstraint(fields=('rgb_color',), name='unique_good_color'),
        ),
    ]
