# Generated by Django 3.2.9 on 2021-11-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20211111_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametersetplayer',
            options={'ordering': ['location', 'id_label'], 'verbose_name': 'Parameter Set Player', 'verbose_name_plural': 'Parameter Set Players'},
        ),
        migrations.AddField(
            model_name='parametersetplayer',
            name='town',
            field=models.IntegerField(default=1, verbose_name='Town number (1-3)'),
        ),
        migrations.AlterField(
            model_name='parametersetplayer',
            name='location',
            field=models.IntegerField(default=1, verbose_name='Location number (1-24)'),
        ),
        migrations.AlterField(
            model_name='parametersetplayergroup',
            name='group_number',
            field=models.IntegerField(default=1, verbose_name='Group Number (1-24)'),
        ),
    ]
