# Generated by Django 3.2.9 on 2021-11-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_parametersetplayer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='number_of_goods',
            field=models.IntegerField(default=2, verbose_name='Number of Goods'),
        ),
    ]
