# Generated by Django 3.2.8 on 2021-11-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_sessionplayer_good_three_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetplayer',
            name='subject_type',
            field=models.CharField(choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four')], default='One', max_length=100),
        ),
        migrations.AlterField(
            model_name='parametersettype',
            name='subject_type',
            field=models.CharField(choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four')], default='One', max_length=100),
        ),
    ]
