# Generated by Django 3.2.9 on 2021-11-18 02:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20211116_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametersettype',
            options={'ordering': ['id'], 'verbose_name': 'Parameter Set Type', 'verbose_name_plural': 'Parameter Set Types'},
        ),
        migrations.AddField(
            model_name='sessionplayer',
            name='player_number',
            field=models.IntegerField(default=0, verbose_name='Player number'),
        ),
        migrations.AddField(
            model_name='sessionplayer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Player Key'),
        ),
    ]
