# Generated by Django 3.2.8 on 2021-11-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20211118_0236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionplayer',
            options={'ordering': ['parameter_set_player__town', 'parameter_set_player__location'], 'verbose_name': 'Session Player', 'verbose_name_plural': 'Session Players'},
        ),
        migrations.AddField(
            model_name='sessionplayermove',
            name='good_three_amount',
            field=models.IntegerField(default=0, verbose_name='Good three amount'),
            preserve_default=False,
        ),
    ]
