# Generated by Django 3.2.9 on 2021-11-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20211119_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionplayer',
            old_name='uuid',
            new_name='player_key',
        ),
        migrations.AddConstraint(
            model_name='sessionplayermove',
            constraint=models.CheckConstraint(check=models.Q(('good_three_amount__gte', 0)), name='good_three_amount__gte_0'),
        ),
    ]
