# Generated by Django 3.2.9 on 2021-11-23 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20211122_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionplayermove',
            name='session_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_player_moves_a', to='main.sessionperiod'),
        ),
        migrations.AlterField(
            model_name='sessionplayermove',
            name='session_player_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_player_moves_b', to='main.sessionplayer'),
        ),
        migrations.AlterField(
            model_name='sessionplayermove',
            name='session_player_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_player_moves_c', to='main.sessionplayer'),
        ),
    ]
