# Generated by Django 3.2.9 on 2021-11-23 18:23

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20211123_1822'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sessionplayermove',
            name='source_equals_target',
        ),
        migrations.AddConstraint(
            model_name='sessionplayermove',
            constraint=models.CheckConstraint(check=models.Q(('session_player_source', django.db.models.expressions.F('session_player_target')), _negated=True), name='source_equals_target'),
        ),
    ]
