# Generated by Django 3.2.9 on 2021-11-23 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20211123_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionplayermove',
            name='source_container',
            field=models.CharField(choices=[('House', 'House'), ('Field', 'Field')], max_length=100, verbose_name='Source Container'),
        ),
        migrations.AlterField(
            model_name='sessionplayermove',
            name='target_container',
            field=models.CharField(choices=[('House', 'House'), ('Field', 'Field')], max_length=100, verbose_name='Target Container'),
        ),
        migrations.CreateModel(
            name='SessionPlayerChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Chat here', max_length=1000, verbose_name='Chat Text')),
                ('chat_type', models.CharField(choices=[('All', 'All'), ('Individual', 'Individual')], max_length=100, verbose_name='Chat Type')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('session_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_player_chats_a', to='main.sessionperiod')),
                ('session_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_player_chats_b', to='main.sessionplayer')),
                ('session_player_recipients', models.ManyToManyField(related_name='session_player_chats_c', to='main.SessionPlayer')),
            ],
            options={
                'verbose_name': 'Session Player Chat',
                'verbose_name_plural': 'Session Player Chats',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='sessionplayerchat',
            constraint=models.CheckConstraint(check=models.Q(('text', ''), _negated=True), name='text_not_empty'),
        ),
    ]
