# Generated by Django 3.2.8 on 2021-12-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20211123_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='private_chat',
            field=models.BooleanField(default=True, verbose_name='Private Chat'),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='allow_stealing',
            field=models.BooleanField(default=False, verbose_name='Allow Stealing'),
        ),
    ]
