# Generated by Django 3.2.8 on 2021-12-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20211201_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='current_period_phase',
            field=models.CharField(choices=[('Production', 'Production'), ('Trade', 'Trade')], default='Production', max_length=100),
        ),
        migrations.AddField(
            model_name='session',
            name='time_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='timer_running',
            field=models.BooleanField(default=False),
        ),
    ]
