# Generated by Django 3.2.9 on 2021-12-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20211201_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayer',
            name='earnings',
            field=models.IntegerField(default=0, verbose_name='Earnings in cents'),
        ),
    ]
