# Generated by Django 3.2.8 on 2021-12-03 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_parametersetplayer_subject_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametersetplayer',
            old_name='subject_type',
            new_name='parameter_set_type',
        ),
    ]
