# Generated by Django 3.2.8 on 2021-12-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_rename_subject_type_parametersetplayer_parameter_set_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionplayer',
            name='good_one_field',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=10, verbose_name='Good one in field'),
        ),
        migrations.AlterField(
            model_name='sessionplayer',
            name='good_two_field',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=10, verbose_name='Good two in field'),
        ),
    ]
