# Generated by Django 3.2.8 on 2021-12-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20211203_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionplayer',
            name='good_one_house',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Good one in house'),
        ),
        migrations.AlterField(
            model_name='sessionplayer',
            name='good_three_house',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Good three in house'),
        ),
        migrations.AlterField(
            model_name='sessionplayer',
            name='good_two_house',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Good two in house'),
        ),
    ]
