# Generated by Django 3.2.9 on 2021-12-06 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20211203_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPlayerPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_one_production', models.IntegerField(verbose_name='Good one amount')),
                ('good_two_production', models.IntegerField(verbose_name='Good two amount')),
                ('good_one_consumption', models.IntegerField(verbose_name='Good one amount')),
                ('good_two_consumption', models.IntegerField(verbose_name='Good two amount')),
                ('good_three_consumption', models.IntegerField(verbose_name='Good two amount')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('session_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_player_periods_a', to='main.sessionperiod')),
                ('session_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_player_periods_b', to='main.sessionplayer')),
            ],
            options={
                'verbose_name': 'Session Player Period',
                'verbose_name_plural': 'Session Player Periods',
                'ordering': ['session_period__period_number'],
            },
        ),
    ]
