# Generated by Django 3.2.8 on 2021-12-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_sessionplayerperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionplayerperiod',
            name='good_one_consumption',
            field=models.IntegerField(default=0, verbose_name='Good one amount'),
        ),
        migrations.AlterField(
            model_name='sessionplayerperiod',
            name='good_one_production',
            field=models.IntegerField(default=0, verbose_name='Good one amount'),
        ),
        migrations.AlterField(
            model_name='sessionplayerperiod',
            name='good_three_consumption',
            field=models.IntegerField(default=0, verbose_name='Good two amount'),
        ),
        migrations.AlterField(
            model_name='sessionplayerperiod',
            name='good_two_consumption',
            field=models.IntegerField(default=0, verbose_name='Good two amount'),
        ),
        migrations.AlterField(
            model_name='sessionplayerperiod',
            name='good_two_production',
            field=models.IntegerField(default=0, verbose_name='Good two amount'),
        ),
    ]
