# Generated by Django 3.2.8 on 2021-12-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20211206_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionplayerperiod',
            options={'ordering': ['session_player__session', 'session_player', 'session_period__period_number'], 'verbose_name': 'Session Player Period', 'verbose_name_plural': 'Session Player Periods'},
        ),
        migrations.AddConstraint(
            model_name='sessionplayerperiod',
            constraint=models.UniqueConstraint(fields=('session_player', 'session_period'), name='unique_session_player_period'),
        ),
    ]
