# Generated by Django 3.2.8 on 2021-12-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20211206_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='earnings',
            field=models.IntegerField(default=0, verbose_name='Period Earnings'),
        ),
    ]
