# Generated by Django 3.2.8 on 2021-12-08 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_sessionplayer_connected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionplayer',
            old_name='connected',
            new_name='connecting',
        ),
    ]
