# Generated by Django 3.2.9 on 2021-12-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_sessionplayer_connected_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='test_mode',
            field=models.BooleanField(default=True, verbose_name='Test Mode'),
        ),
    ]
