# Generated by Django 3.2.8 on 2021-12-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_alter_parameterset_test_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Avatar', max_length=200)),
                ('file_name', models.CharField(default='abc.jpg', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatars',
                'ordering': (['label'],),
            },
        ),
        migrations.AddConstraint(
            model_name='avatars',
            constraint=models.UniqueConstraint(fields=('label',), name='unique_avatar_label'),
        ),
    ]
