# Generated by Django 3.2.8 on 2021-12-10 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20211210_1938'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avatars',
            new_name='Avatar',
        ),
    ]
