# Generated by Django 3.2.8 on 2021-12-10 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_auto_20211210_2111'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='avatar',
            name='unique_avatar_label',
        ),
        migrations.AddField(
            model_name='parametersetplayer',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_players_e', to='main.avatar'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='label',
            field=models.CharField(default='Avatar', max_length=200, unique=True),
        ),
    ]
