# Generated by Django 3.2.8 on 2021-12-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_alter_parametersetplayer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='good_one_production_rate',
            field=models.IntegerField(default=0, verbose_name='Good one production setting 0-100'),
        ),
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='good_two_production_rate',
            field=models.IntegerField(default=0, verbose_name='Good two production setting 0-100'),
        ),
    ]
