# Generated by Django 3.2.9 on 2021-12-15 00:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0069_auto_20211213_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='collaborators',
            field=models.ManyToManyField(related_name='session_collaborators', to=settings.AUTH_USER_MODEL),
        ),
    ]
