# Generated by Django 3.2.9 on 2021-12-15 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0070_session_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='collaborators',
            field=models.ManyToManyField(related_name='sessions_b', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_a', to=settings.AUTH_USER_MODEL),
        ),
    ]
