# Generated by Django 3.2.9 on 2021-12-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_auto_20211215_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayer',
            name='name',
            field=models.CharField(default='Your name here', max_length=100, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='sessionplayer',
            name='student_id',
            field=models.CharField(default='', max_length=100, verbose_name='Student ID'),
        ),
    ]
