# Generated by Django 3.2.9 on 2021-12-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_auto_20211215_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionplayer',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Full Name'),
        ),
    ]
