# Generated by Django 3.2.8 on 2021-12-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_alter_sessionplayer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayerchat',
            name='current_period_phase',
            field=models.CharField(choices=[('Production', 'Production'), ('Trade', 'Trade')], default='Production', max_length=100),
        ),
        migrations.AddField(
            model_name='sessionplayerchat',
            name='time_remaining',
            field=models.IntegerField(default=0, verbose_name='Good one amount'),
        ),
        migrations.AddField(
            model_name='sessionplayermove',
            name='current_period_phase',
            field=models.CharField(choices=[('Production', 'Production'), ('Trade', 'Trade')], default='Production', max_length=100),
        ),
        migrations.AddField(
            model_name='sessionplayermove',
            name='time_remaining',
            field=models.IntegerField(default=0, verbose_name='Good one amount'),
        ),
    ]
