# Generated by Django 3.2.9 on 2021-12-21 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_auto_20211217_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayer',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_players_b', to='main.avatar'),
        ),
    ]
