# Generated by Django 3.2.9 on 2021-12-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_sessionplayer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='avatar_assignment_mode',
            field=models.CharField(choices=[('None', 'None'), ('Pre-Assigned', 'Pre-Assigned'), ('Subject Select', 'Subject Select'), ('Best Match', 'Best Match')], default='None', max_length=100),
        ),
    ]
