# Generated by Django 3.2.9 on 2021-12-22 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_parameterset_avatar_assignment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSetAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_location_row', models.IntegerField(default=1, verbose_name='Grid Location Row')),
                ('grid_location_col', models.IntegerField(default=1, verbose_name='Rid Location Column')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_avatars_b', to='main.avatar')),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_avatars_a', to='main.parameterset')),
            ],
            options={
                'verbose_name': 'Parameter Set Avatar',
                'verbose_name_plural': 'Parameter Set Avatars',
                'ordering': ['grid_location_row', 'grid_location_col'],
            },
        ),
    ]
