# Generated by Django 3.2.9 on 2021-12-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_auto_20211222_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='avatar_grid_text',
            field=models.CharField(default='Choose an avatar that best represents you.', max_length=300, verbose_name='Avatar Grid Text'),
        ),
    ]
