# Generated by Django 3.2.9 on 2021-12-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_session_current_experiment_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='show_instructions',
            field=models.BooleanField(default=True, verbose_name='Show Instructions'),
        ),
    ]
