# Generated by Django 3.2.9 on 2021-12-30 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_parameterset_show_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetplayer',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_players_e', to='main.avatar'),
        ),
    ]
