# Generated by Django 3.2.9 on 2022-01-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_alter_session_current_experiment_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Page Name', max_length=100, verbose_name='Label')),
                ('text', models.CharField(default='Chat here', max_length=1000, verbose_name='Page Text')),
                ('page_number', models.IntegerField(default=1, verbose_name='Page Number')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instruction Page',
                'verbose_name_plural': 'Instruction Pages',
                'ordering': ['page_number'],
            },
        ),
    ]
