# Generated by Django 3.2.9 on 2022-01-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_alter_instruction_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayer',
            name='current_instruction',
            field=models.IntegerField(default=0, verbose_name='Current Instruction'),
        ),
        migrations.AddField(
            model_name='sessionplayer',
            name='current_instruction_complete',
            field=models.IntegerField(default=0, verbose_name='Current Instruction Complete'),
        ),
    ]
