# Generated by Django 3.2.9 on 2022-01-04 02:06

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_sessionplayer_instructions_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='text_html',
            field=tinymce.models.HTMLField(default='Text here', verbose_name='Page HTML Text'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='text',
            field=models.CharField(default='Text here', max_length=100000, verbose_name='Page Text'),
        ),
    ]
