# Generated by Django 3.2.9 on 2022-01-04 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_instruction_instruction_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='instruction_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='main.instructionset'),
        ),
    ]
