# Generated by Django 3.2.9 on 2022-01-04 18:45

from django.db import migrations, models
import django.db.models.deletion

import main

def do_python(apps, schema_editor):
    
    instruction_set = main.models.InstructionSet.objects.first()

    if not instruction_set:
        instruction_set = main.models.InstructionSet()
        instruction_set.save()
    
    main.models.ParameterSet.objects.all().update(instruction_set=instruction_set)

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_alter_instruction_instruction_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='instruction_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_sets', to='main.instructionset'),
        ),
        migrations.RunPython(do_python),
    ]
