# Generated by Django 3.2.11 on 2022-01-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_auto_20220111_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayernotice',
            name='show_on_staff',
            field=models.BooleanField(default=False, verbose_name='Show Notice on Staff Screen'),
        ),
    ]
