# Generated by Django 3.2.11 on 2022-01-12 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_auto_20220112_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='test_email_account',
        ),
    ]
