# Generated by Django 3.2.11 on 2022-01-13 21:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_sessionplayer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='invitation_text',
            field=tinymce.models.HTMLField(default='', verbose_name='Invitation Text'),
        ),
        migrations.AddField(
            model_name='session',
            name='invitation_text',
            field=tinymce.models.HTMLField(default='', verbose_name='Invitation Text'),
        ),
    ]
