# Generated by Django 3.2.11 on 2022-01-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_auto_20220113_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='invitation_text_subject',
            field=models.CharField(default='', max_length=200, verbose_name='Invitation Subject'),
        ),
    ]
