# Generated by Django 3.2.11 on 2022-01-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0102_parameters_invitation_text_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameters',
            old_name='invitation_text_subject',
            new_name='invitation_subject',
        ),
    ]
