# Generated by Django 3.2.11 on 2022-01-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0104_session_invitation_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionplayer',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Address'),
        ),
    ]
