# Generated by Django 3.2.11 on 2022-01-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0105_alter_sessionplayer_email'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sessionplayer',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', True)), fields=('session', 'email'), name='unique_email_session_player'),
        ),
    ]
