# Generated by Django 3.2.11 on 2022-01-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0106_sessionplayer_unique_email_session_player'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sessionplayer',
            name='unique_email_session_player',
        ),
        migrations.AddConstraint(
            model_name='sessionplayer',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('session', 'email'), name='unique_email_session_player'),
        ),
    ]
