# Generated by Django 3.2.11 on 2022-03-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0107_auto_20220114_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='group_chat',
            field=models.BooleanField(default=True, verbose_name='Group Chat'),
        ),
    ]
