# Generated by Django 3.2.12 on 2022-04-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0108_parameterset_group_chat'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='instructionset',
        #     name='action_page_chat',
        #     field=models.IntegerField(default=4, verbose_name='Required Action: Chat'),
        # ),
        # migrations.AddField(
        #     model_name='instructionset',
        #     name='action_page_move',
        #     field=models.IntegerField(default=3, verbose_name='Required Action: Move'),
        # ),
        # migrations.AddField(
        #     model_name='instructionset',
        #     name='action_page_production',
        #     field=models.IntegerField(default=2, verbose_name='Required Action: Production'),
        # ),
    ]
