# Generated by Django 4.0.7 on 2022-09-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0109_auto_20220418_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersettype',
            name='ce_earnings',
            field=models.DecimalField(decimal_places=2, default=90, max_digits=10, verbose_name='Earnings at Completive Equilibrium'),
        ),
    ]
