# Generated by Django 4.0.7 on 2022-09-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0110_parametersettype_ce_earnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersettype',
            name='ce_earnings',
            field=models.IntegerField(default=90, verbose_name='Earnings at Completive Equilibrium'),
        ),
    ]
