# Generated by Django 4.0.7 on 2022-09-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0111_alter_parametersettype_ce_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='efficiency',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Efficiency'),
        ),
    ]
