# Generated by Django 4.0.7 on 2022-09-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0112_sessionplayerperiod_efficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersettype',
            name='autarky_earnings',
            field=models.IntegerField(default=30, verbose_name='Earnings at Autarky'),
        ),
    ]
