# Generated by Django 4.0.7 on 2022-11-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0114_parameterset_survey_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetplayer',
            name='survey_complete',
            field=models.BooleanField(default=False, verbose_name='Survey Complete'),
        ),
    ]
