# Generated by Django 4.1.3 on 2022-11-29 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0117_alter_sessionplayer_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sessionplayer',
            name='unique_email_session_player',
        ),
    ]
