# Generated by Django 4.1.5 on 2023-03-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0120_parameterset_collect_names_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='collect_names',
        ),
        migrations.AddField(
            model_name='parameterset',
            name='prolific_mode',
            field=models.BooleanField(default=False, verbose_name='Prolific Mode'),
        ),
    ]
