# Generated by Django 4.1.7 on 2023-03-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0123_remove_parameterset_prolific_session_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='prolific_session_id',
        ),
        migrations.RemoveField(
            model_name='session',
            name='prolific_study_id',
        ),
        migrations.AddField(
            model_name='parameterset',
            name='prolific_session_id',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Prolific session ID'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='prolific_study_id',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Prolific Study ID'),
        ),
    ]
