# Generated by Django 4.1.7 on 2023-03-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0124_remove_session_prolific_session_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='prolific_session_id',
        ),
    ]
