# Generated by Django 4.1.7 on 2023-03-09 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0125_remove_parameterset_prolific_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='prolific_study_id',
        ),
    ]
