# Generated by Django 4.2.9 on 2024-02-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0126_remove_parameterset_prolific_study_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='information_mode',
            field=models.CharField(choices=[('None', 'None'), ('Production', 'Production')], default='None', max_length=100),
        ),
    ]
