# Generated by Django 4.2.16 on 2024-09-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0129_parameterset_json_for_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='id_string',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
