# Generated by Django 4.2.16 on 2024-10-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0131_parameterset_reconnection_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='controlling_channel',
            field=models.CharField(default='', max_length=300),
        ),
    ]
