# Generated by Django 4.2.16 on 2024-10-11 21:02

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0132_session_controlling_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='world_state',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Current Session State'),
        ),
    ]
