# Generated by Django 4.2.16 on 2024-10-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0133_session_world_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionplayerperiod',
            name='efficiency',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='Efficiency'),
        ),
    ]
