# Generated by Django 4.2.16 on 2024-11-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0134_alter_sessionplayerperiod_efficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='good_one_field',
            field=models.IntegerField(default=-1, verbose_name='Good one field'),
        ),
        migrations.AddField(
            model_name='sessionplayerperiod',
            name='good_two_field',
            field=models.IntegerField(default=-1, verbose_name='Good two field'),
        ),
    ]
