# Generated by Django 4.2.16 on 2024-11-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0135_sessionplayerperiod_good_one_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayer',
            name='good_one_field_production',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=12, verbose_name='Good one in field'),
        ),
        migrations.AddField(
            model_name='sessionplayer',
            name='good_two_field_production',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=12, verbose_name='Good two in field'),
        ),
        migrations.AlterField(
            model_name='sessionplayer',
            name='good_one_house',
            field=models.IntegerField(default=0, verbose_name='Good one in house'),
        ),
        migrations.AlterField(
            model_name='sessionplayer',
            name='good_three_house',
            field=models.IntegerField(default=0, verbose_name='Good three in house'),
        ),
        migrations.AlterField(
            model_name='sessionplayer',
            name='good_two_house',
            field=models.IntegerField(default=0, verbose_name='Good two in house'),
        ),
    ]
